### ISSUE TITLE
scaffold upload from gff3 and fasta

### ISSUE THREAD

**Issue by Aditya-Upa** [computational-genomics-lab/galEupy#1]
if the scaffold information is missing from the gff3 file, it is not uploading the scaffold which is there in genomic fasta file

**Comment by arpanda** [comment]
The following changes were made to address the above issue:

- All contigs/scaffolds from the FASTA file are now loaded.
- An additional check has been added to detect any complete mismatch between the GFF and FASTA files. Processing will only proceed if `at least one contig/scafoold matches`.

-Arijit
