### ISSUE TITLE
update gene prefix 

### ISSUE THREAD

**Issue by Aditya-Upa** [computational-genomics-lab/galEupy#2]
three letters from genus
four letters from species
example : For Phytophthora sojae, gene prefix will be Physoja instead of Physo

**Comment by Aditya-Upa** [comment]
after annotation, gff files look like this :
JAIKVF010000001.1       funannotate     gene    534     1529    .       -       .       ID=g1;name=g1;product=
JAIKVF010000001.1       funannotate     mRNA    534     1529    .       -       .       ID=g1.t1;Parent=g1;product=-;note=EggNog:ENOG503QAM1,SECRETED:SignalP(1-23,SECRETED:cutsite-VDA-HG,SECRETED:prob-0.7168)
JAIKVF010000001.1       funannotate     exon    534     1529    .       -       .       ID=g1.t1.exon1;Parent=g1.t1

if the species is Phytophthora melonis then the genes are named as Phyme_g1 in the database after uploading through galEupy. 

Species name if available must be incorporated in this naming scheme. Suppose species is CJ26. According to new convention the gene name will be Phymelo_CJ26_g1 for gene g1.

**Comment by arpanda** [comment]
Updated the organism prefix.
